# Generated by Django 3.1.7 on 2021-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210316_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_feautured',
            field=models.BooleanField(default=False),
        ),
    ]
