# Generated by Django 3.1.7 on 2021-03-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_feautured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_feautured',
            new_name='is_featured',
        ),
    ]
