# Generated by Django 3.1.7 on 2021-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.IntegerField(default=2022104),
            preserve_default=False,
        ),
    ]
