# Generated by Django 3.1.7 on 2021-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1234123, max_length=100),
            preserve_default=False,
        ),
    ]
